### ISSUE TITLE
下载下来了 项目运行不了

### ISSUE THREAD

**Issue by DavidWuJay** [FatDong1/VueBlog#1]
已经按照您说的操作了

**Comment by rudyxu1102** [comment]
到哪一步出错了呢？截图发一下错误信息

**Comment by DavidWuJay** [comment]
![Uploading mangoDB.png…]()
![Uploading npmrunstart.png…]()
![Uploading error22pas.png…]()

**Comment by DavidWuJay** [comment]
![Uploading localhost.png…]()
![Uploading mangoDB.png…]()
![Uploading npmrunstart.png…]()
![Uploading error22pas.png…]()
