### ISSUE TITLE
服务器起不来啊！你看看截图

### ISSUE THREAD

**Issue by Nicederen** [FatDong1/VueBlog#4]
![image](https://user-images.githubusercontent.com/26369769/29602325-43bc3e5c-8812-11e7-98ea-12523ee8683e.png)

**Comment by Nicederen** [comment]
好像是数据库版本不兼容

**Comment by rudyxu1102** [comment]
看错误原因ES6代码没有编译成ES5，不好意思
(´;︵;`)最近身边没有电脑，没法详细给你说明，之前按照我自己的步骤是可以正常运行的，建议重新按照readme.md的步骤重新走一遍
